[package]
name = "koto_poetry"
version = "0.17.0"
autobins = false
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true

[[example]]
name = "poetry"
path = "src/main.rs"

[dependencies]
koto = { workspace = true, features = ["rc"] }
koto_random = { workspace = true }

anyhow = { workspace = true }
hotwatch = { workspace = true }
indexmap = { workspace = true }
lazy_static = { workspace = true }
pico-args = { workspace = true }
rand = { workspace = true, features = ["std", "thread_rng"] }
