[package]
name = "koto_poetry"
version = "0.15.3"
autobins = false
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true

[[example]]
name = "poetry"
path = "src/main.rs"

[dependencies]
koto = { path = "../../", version = "^0.15.3" }
koto_random = { path = "../../../../libs/random", version = "^0.15.3" }

anyhow = { workspace = true }
hotwatch = { workspace = true }
indexmap = { workspace = true }
lazy_static = { workspace = true }
pico-args = { workspace = true }
rand = { workspace = true }
